sudo: required
services:
- docker
language: java
jdk:
- oraclejdk8
branches:
  only:
    - master
env:
  matrix:
  - TEST_DIR=client
  - TEST_DIR=server
  global:
  - REGISTRY_USERNAME=cloudesirejenkins
  - BLOB_IDENTITY=cloudesire-deployer
  - DOCKER_COMPOSE_VERSION=1.5.2
  - CI_DEPLOY_GPG_KEYID=F5DF9FC4
  - CI_DEPLOY_USERNAME=gionn
  - secure: GjEZzKw05UxIc/3+ykBWJdlbVB8zK7RZT0PI2xd4+ecyodiybobBf2ILLS5ao+Kn71wl1VgB7xz0EMh4zoJYRiehdN+2yKcoY1KCgvvTSYTHEjvlgPGjmB1VMEcqZZmd5NFE2rHeJpSHqS3tE7dJeWlSOHUeeKJT3RTaIUiGFpA3HnL1mPf8T2hir7ys+LHUsM/0eF8ry18fvYKqs5x0gag8pLrZaIU+AbGVgLtAsLJkjAettzjes/ivfkLeWNj6dlcGS4AuSb5uNbpBa8vFzryQhugXohni8iHyPLNRe2KRpbHZuC39FPUZdPwZ86JaHNa4zoyjLPm8+9fcV4LEVU6CPTeBl/TvL4oF51BnCus+F6oP/KHt2NncbOJR2NeC4nzxpJj9euPiPx6H8qDqsZLjZyaB52R755RRjwjbMCSGKbfQZmXHi+P2g+uWYISVhTkjVJ3Wk1UPRqg8BZbwUHSfk+ev3yjHcnv2Gdvk428Y7mw7RaQdVSJaODds1daqdfBMsn+3nBivLTG4iM04HLfThFQvbZ+FNawz8W8A1HWNTfReYIPm7bltDV8vi7iPW4uYafcx+Dp5A78kzV5GYTk/avWBXKTo5HyBZ7vW1cfjLe+Dy/SGdwf+DhOTGgo2Z3dCwxt12+y4zlV1N4u66H2uJPqVggZtJQB/QhfoCek=
  - secure: kyZpJgwyqRpRh3c6IUxxBzukHZSdcisLNNBDbLYwUJDnu215J58nXtgIQHTD6CG1yar3KmRGGh2cDNpFeDrZVEdLUKMC8XHXSlVSP78AeD6MJHBRzkDMRdWemk+uW836YbCRl9LQw5L1MTwq91JpyZv1MU7RGgMs8Yg4mr0WId32Y3yW4SsTUh5zHxTJ9pQfAQQa/4azAjtugIfZ42w62lwTK+oO/GulcJCbHrHp/RDEqS6qtkKNXFHSo5woKj5qVPTJwA8+dwhSOXJJSTK56xDFh+yOEeXaZKjwMYHvOxrPZbuCZeAPzlQcrWH72W5dAwHBBKjvreNsrsZSgkDWnakPe6ZMkPYk0aqqp89WBnrv5ohe3w5a8kUFI6qjwsoOnvljy1ONA5A0KIALybYsoM4psAgEPcinOSl56XsfO1TrzqGXWGN3j5opgUV4K4EMbuAtgBOp5cRo6Y+btRoWbXWvOvG+6Ti3y5FPBUKP/Dh7PgcU5FjfxDaUyNaL2b7TFI63jhDUrZyOV5GowfXEQXSzcw1L2WVz7v74H4m1sZ1juIbnn5rdmR8p88KxTcQISm2wBVVaWHH72SUJ22Qw6QludoTsGUhv9yEmkCoEuC+AeHEKphYqJJvIS0xjEF1RaimQ7TPbmGC1TyBp8V4XhnECArIOwQHdabvsQNGzt6g=
  - secure: UQiFROyzT/HNqe/sUlJQ5gDc9eJQH7oUB8AqvVLtR7W6VjzNHj0utZREaDO8XjRT1u1rPR10nSfysRsiEuCYsODGonEGw6Yz5ELkCYDIB+9OtTQc1Jk25/gH2fEBR9rE2Z1aHxcIqMcjLLYIJ/zbs7qIbUG0L65EhRZy9+MXD0oT94Gpz4aB0XDzqyi6mNSe1Zt0Vessgi4xYZSd10HFs6kwFpbA2lfmFhRkkbbfw2kUGjTXg0bZS6RYQClChBTWcAMrvJ+kJJHfBFyojtpqJLIQ0eguOOmGrZkr8ANsICwI4eS7yqHVpATXXxLrr2iBdv/k23/KjxYd+FNiv3CYfm3t2AksD58zsSn/Wqsd55eB2ash3t/8kuclItY4P92V9IU+jq0pdQPC9XuvXlvvoZRZKKAhygJbRektPMLgRwuG/rHOSGgQrMlgtI2gw6z88Llcds0iVU3UEI+sqwOJaLayi45FdjnymbdC5AvoMue4hMbnwydqZKcxp11pYXZxbolNIuf0wC3YT0OsV4uiwL65UesuvGTzQNBcKY8JhtmIe/dhvCkAH7piI4s29aU0gg0DUL07R4MnowCd4WIQTvKOSTbAKSBA5QAbv4dPsiHtfxB3VggKebMUmarkrXW+jkn0/hn4Ymcmfhpg2sTLdCaRHHu2kXU7L78jEKdy4mg=
before_install:
- openssl aes-256-cbc -K $encrypted_0f52e8f83e31_key -iv $encrypted_0f52e8f83e31_iv -in .travis/private.gpg.enc -out .travis/private.gpg -d
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
install: /usr/local/bin/docker-compose -f docker-compose.yml up -d
script: cd $TEST_DIR && mvn install --settings ../.travis/settings.xml
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
