language: java
jdk:
  - oraclejdk8
  - oraclejdk7
env:
- TEST_DIR=client
- TEST_DIR=server
install: cd $TEST_DIR && mvn install -Dmaven.test.skip=true
script: mvn test
cache:
  directories:
  - $HOME/.m2
