sudo: required
services:
  - docker
language: java
jdk:
  - oraclejdk8
env:
- TEST_DIR=client
- TEST_DIR=server
install: cd $TEST_DIR && mvn install -Dmaven.test.skip=true
script:  docker-compose up -d -f ../docker-compose.yml && mvn test
cache:
  directories:
  - $HOME/.m2
