version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8u181-jdk
      - image: redis
    steps:
      - checkout
      - run:
          name: Get common configs
          command: git clone git@github.com:ClouDesire/ci-conf.git ~/repo/conf
      - restore_cache:
          keys:
            - m2-{{ checksum "janine-client/pom.xml" }}
            - m2-
      - run:
          name: Configure Maven repository
          command: mkdir -p ~/.m2 && cp ~/repo/conf/mvn/settings.xml ~/.m2
      - run:
          name: Build
          command: ./mvnw -B install -Dmaven.test.skip=true
      - save_cache:
          key: janine-root
          paths:
            - "~/.m2"
      - run:
          name: Run Tests
          command: ./mvnw -B verify
      - run:
          name: Deploy client artifacts
          command: ./mvnw -B deploy -Dmaven.test.skip=true
      - setup_remote_docker
      - run:
          name: Deploy client artifact and build docker server image
          command: if [ "$CIRCLE_BRANCH" == "master" ]; then ./deploy.sh; fi
